Changed ScriptWidget QLineEdit to QComboDropbox that loads all .py fi…
LabGUI/LabGUI pull request #34
Opened 2019-09-13 17:38 UTC by zackorenberg

Very simple feature. Instead of a QLineEdit for ScriptWidget (selects user script to run), I used a QComboBox that loads all *.py scripts in the selected file's directory, selectable via up/down arrows. This is useful for when a user is working with multiple script files.

2019-09-13 17:40 UTC, zackorenberg reviewed
I added support for the legacy version using QLineEdit

2019-09-14 14:26 UTC, Bachibouzouk requested changes
Thanks for improving LabGui @zackorenberg 

Comments on the code : 

If it is an improvement, then why would we need to keep a LEGACY version? I don't think this would be a breaking change with the previous version.  Having too many options to choose from makes things more difficult for developers and maintainers.
LineEdit was chosen in the past because we trusted our "standard user" to be geek enough to write down a path in an empty box. As long as the option to choose any path is still there, I see the combobox as an improvment of the comfort of the user without a decrease in usability (which I find good :))

Therefore I would be in favor to keep only the combobox :)

Meta comments on github workflow:

- Thanks for making a PR with not too many changes, it is really enjoyable to review :)
- You could have made two commits : 1 with legacy and 1 with only the new code (i.e. function only used by combobox)
- You can also modify the changelog in a commit, so the description of the changes are done now
- You could have opened an issue describing why you wanted to make these changes to the code and where we could have chatted about the possible solution, thus avoiding you to write the LEGACY code if it ends up not being used ;)

2019-09-14 14:26 UTC, Bachibouzouk commented on LabTools/CoreWidgets/ScriptWidget.py
> +    def __init__(self, parent=None, LEGACY = None):
```suggestion
    def __init__(self, parent=None, legacy=None):
```
function arguments should be small caps

2019-09-14 14:26 UTC, Bachibouzouk commented on LabTools/CoreWidgets/ScriptWidget.py
> +            self.LEGACY = LEGACY
```suggestion
            self.LEGACY = legacy
```

2019-09-14 14:26 UTC, Bachibouzouk commented on LabTools/CoreWidgets/ScriptWidget.py
> +            self.LEGACY = LEGACY
@zackorenberg - you can "add suggestion to batch" with the lower right button under my suggestion to bind the suggestion together :)

2019-09-14 14:26 UTC, Bachibouzouk commented on LabTools/CoreWidgets/ScriptWidget.py
> +    #parent.widgets['ScriptWidget'].scriptFileLineEdit.setText(fname)
please do not push code which is commented out :)
Possible solution for that now:
- checkout your branch: `git checkout feature/dropdown_script_selector`
- erase the line locally and stage the change with `git add LabTools/CoreWidgets/ScriptWidgets.py`
- melt this change in the previous commit: `git commit --amend`
- force push your changes on the remote (only do that when the other people working on the branch are aware of it, i.e. tell them beforehand) : `git push -f`

2019-09-25 14:01 UTC, zackorenberg commented
@Bachibouzouk I have amended the changes you requested to ScriptWidget.py. I left the legacy version as an option because I felt there was no real reason to delete the old functionality of ScriptWidget.py, as the changes I made were ultimately small. Should anyone wish to use this module in the LabGUI library for whatever reason, they will have the option to use the LineEdit by invoking legacy=True in the constructor.

2019-11-19 19:47 UTC, zackorenberg commented
@Bachibouzouk what do you think?

2019-11-19 20:05 UTC, Bachibouzouk approved these changes
I approve your changes :)

2019-11-19 20:49 UTC, merged